export enum DoctorSpecialty {
  GENERAL_PRACTIONER = 'GENERAL_PRACTIONER',
  PEDIATRICIAN = 'PEDIATRICIAN',
  DERMATOLOGIST = 'DERMATOLOGIST',
  PSYCHIATRIST = 'PSYCHIATRIST',
  THERAPIST = 'THERAPIST',
  OPHTHALMOLOGIST = 'OPHTHALMOLOGIST',
  NUTRITIONIST = 'NUTRITIONIST',
  CARDIOLOGIST = 'CARDIOLOGIST',
  GYNECOLOGIST = 'GYNECOLOGIST',
  ORTHOPEDIC_SURGEON = 'ORTHOPEDIC_SURGEON',
  ENT_SPECIALIST = 'ENT_SPECIALIST',
}
