export enum ConsultationType {
  GENERAL_PRACTITIONER = 'GENERAL_PRACTITIONER',
  PEDIATRICIAN = 'PEDIATRICIAN',
  DERMATOLOGIST = 'DERMATOLOGIST',
  PSYCHIATRIST = 'PSYCHIATRIST',
  THERAPIST = 'THERAPIST',
  OPHTHALMOLOGIST = 'OPHTHALMOLOGIST',
  NUTRITIONIST = 'NUTRITIONIST',
  CARDIOLOGIST = 'CARDIOLOGIST',
  GYNECOLOGIST = 'GYNECOLOGIST',
  ORTHOPEDIC_SURGEON = 'ORTHOPEDIC_SURGEON',
  ENT_SPECIALIST = 'ENT_SPECIALIST',
  OTHER = 'OTHER',
}
