export enum ConsultationStatus {
  PENDING_ACCEPTANCE = 'PENDING_ACCEPTANCE',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
  ACKNOWLEDGED = 'ACKNOWLEDGED',
  BOOKED = 'BOOKED',
}
