export enum OnboardingType {
  EMAIL_VERIFIED = 'EMAIL_VERIFIED',
  MOBILE_VERIFIED = 'MOBILE_VERIFIED',
  SET_LOCATION = 'SET_LOCATION',
  //VENDOR
  ACTIVATE_STORE = 'ACTIVATE_STORE',
  CREDENTIAL_VERIFICATION = 'CREDENTIAL_VERIFICATION',
  SETUP_OPERATIONS = 'SETUP_OPERATIONS',
  ADD_STORE_INFO = 'ADD_STORE_INFO',
  CREATE_MENU = 'CREATE_MENU',
}
