export enum TransactionCategory {
  CREDIT = 'CREDIT',
  LOGISTICS = 'LOGISTICS', //debit
  Q_COMMERCE = 'Q_COMMERCE', //debit
  ORDER = 'ORDER', // credit
  DEBIT = 'DEBIT',
  FUND_WALLET = 'FUND_WALLET', // credit
  ORDER_REFUND = 'ORDER_REFUND',
  ORDER_DEBIT = 'ORDER_DEBIT',
  CONSULTATION_REWARD = 'CONSULTATION_REWARD',
  CONSULTATION_DEBIT = 'CONSULTATION_DEBIT',
}
