export enum OtpPurpose {
  VERIFICATION = 'VERIFICATION',
  PASSWORD_RESET = 'PASSWORD_RESET',
  ADMIN_LOGIN = 'ADMIN_LOGIN',
  STORE_DELETION = 'STORE_DELETION',
  STORE_PASSWORD_RESET = 'STORE_PASSWORD_RESET',
}
